### ISSUE TITLE
What was it like to learn Ceylon?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/ceylon#94]
We’ve recently [started a project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation) to find the best way to design our tracks, in order to optimize the learning experience of students.

As a first step, we’ll be [examining the ways in which languages are unique and the ways in which they are similar](https://github.com/exercism/exercism/issues/5059). For this, we’d really like to use the knowledge of **everyone** involved in the Exercism community (students, mentors, maintainers) to answer the following questions:

1. How was your experience learning Ceylon? What was helpful while learning Ceylon? What did you struggle with? How did you tackle problems?
1. In what ways did Ceylon differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Could you spare 5 minutes to help us by answering these questions? It would greatly help us improve the experience students have learning Ceylon :)

_Note: this issue is **not** meant as a discussion, just as a place for people to post their own, personal experiences._

_Want to keep your thoughts private but still help? Feel free to email me at erik@exercism.io_

Thank you!

**Comment by petertseng** [comment]
You cannot give anyone a reference to `this` in your initialiser, as stated in https://ceylon-lang.org/documentation/1.3/tour/initialization/. As the page states, "Unfortunately, these rules make it a little tricky to set up circular references between two objects." This comes up as an issue in exercises like `react`, and perhaps others that are not yet implemented.

**Comment by petertseng** [comment]
EBWODP: In general, it seemed to me that in most instances where the language design had a choice between "make the rules strict to forbid people from doing the wrong thing (but also sometimes forbidding programs that would otherwise be valid)" and "make the rules lenient to allow more programs (but some of them will do the wrong thing)" Ceylon chose to make the rules strict. The "can't give anyone a reference to `this` in your initialiser" is just one example (compare to Kotlin's handling - it's one of the few times you can get a NullPointerException in Kotlin).

**Comment by petertseng** [comment]
EBWODP: https://kotlinlang.org/docs/reference/null-safety.html "An uninitialized this available in a constructor is passed and used somewhere ("leaking this");"

**Comment by petertseng** [comment]
A characteristic of Ceylon that is rare is the presence of union types and intersection types in the type system. It's a little hard for me to tell how widespread this is among other languages since searching for the term sometimes gets things mixed up with C's `union` or a *tagged union*, common to many languages. And based on one's definition of these concept, one might argue just how much difference there is between them.

Of the languages known to me, the ones with the most similar feature would be TypeScript (Union and intersection types: http://www.typescriptlang.org/docs/handbook/advanced-types.html) and Crystal (Union types: https://crystal-lang.org/reference/syntax_and_semantics/union_types.html; no intersection types).

I have not thought carefully about whether there would be an exercise that would require the student to use intersection types, but some exercises of the Ceylon track do use union types to describe the possibility of an error: hamming, largest-series-product, rna-transcription.

**Comment by petertseng** [comment]
EBWODP: With some last-minute research, Today I Learned about the presence of union and/or intersection types in Java and Scala. Updated list to list the following:

  * TypeScript: Union and intersection types: http://www.typescriptlang.org/docs/handbook/advanced-types.html
  * Crystal: Union types: https://crystal-lang.org/reference/syntax_and_semantics/union_types.html; no intersection types.
  * Java in certain limited contexts: Union types allowed in `catch` https://docs.oracle.com/javase/8/docs/api/javax/lang/model/type/UnionType.html; Intersection types seem to be allowed more generally https://docs.oracle.com/javase/8/docs/api/javax/lang/model/type/IntersectionType.html but are most commonly used to denote that a type parameter extends two interfaces.
* Scala: Intersection types: http://dcapwell.github.io/scala-tour/Union%20and%20Intersection%20types.html; no union types.

**Comment by petertseng** [comment]
https://en.wikipedia.org/wiki/Intersection_type has section https://en.wikipedia.org/wiki/Intersection_type#Comparison_of_languages_with_intersection_types

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our research for the v3 version of Exercism which has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

Thanks everyone for chipping in! It has been greatly appreciated.
